name: Pull code, rebuid files and restart pm2 processes

on:
  push:
    branches: [main]
    
jobs:
  update: 
    runs-on: ubuntu-latest
    steps:
        - name: Rebuild server
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: |
              cd karpuz.xyz
              git pull
              cd api
              npm install
              npx tsc
              cd ..
              cd client
              npm run build
              pm2 restart server client
            host: ${{ secrets.HOST }}
            username: ${{secrets.USERNAME}}
            privateKey: ${{ secrets.PRIVATE_KEY}}